#app_dir: /usr/share/nginx/html
app_dir: /app
component: frontend
#app_user: nginx
app_user: expense
#log_file_path: /var/log/nginx/access.log
log_file_path: /var/log/frontend.log
rsyslog_config_needed: true
