- name: copy rsyslog file
  ansible.builtin.template:
    src: rsyslog.conf
    dest: /etc/rsyslog.d/{{component}}.conf

- name: restart rsyslog
  ansible.builtin.systemd:
    name: rsyslog
    state: restarted