- name: fetching the secrets from hasicorp vault
  hosts: localhost
#  become: yes
  tasks:
    - name: creating file and saving the common creds
      ansible.builtin.lineinfile:
        path: secrets.json
        line: "{{ lookup('hashi_vault', 'secret=common/ssh token={{vault_token}} url=https://vault.vsldo.online:8200 validate_certs=False')}}"
        create: yes

    - name: creating file and saving the app related creds
      ansible.builtin.lineinfile:
        path: app.json
        line: "{{ lookup('hashi_vault', 'secret={{env}}/{{role_name}} token={{vault_token}} url=https://vault.vsldo.online:8200 validate_certs=False')}}"
        create: yes
