- name: set prompt for system
  ansible.builtin.shell: set-prompt {{ role }}-{{ env }}

- name: Import node_exporter and install
  ansible.builtin.import_role:
    name: prometheus
    tasks_from: node_exporter

- name: Import Logstash and install it
  ansible.builtin.import_role:
    name: logstash
    tasks_from: main
  when: logstash_config_needed

- name: Rsyslog Configuration
  ansible.builtin.import_role:
    name: rsyslog
  when: rsyslog_config_needed